name: Release to Azure service

on:
    workflow_dispatch:

permissions:
    security-events: write
    actions: read
    contents: read
    issues: write
    id-token: write

jobs:
    Build:
        if: github.ref == 'refs/heads/main'
        uses: aoda-zhang/shared-devops/.github/workflows/shared_build.yaml@master
        with:
            app_repository: ${{ github.repository }}
            app_branch: ${{ github.ref }}
            config_folder: honey-service
            currentEnvironment: PROD
            build_name: honey-service-PROD
            build_script: build:PROD
            build_path: dist
            isZipDeploy: YES
        secrets:
            PAT: ${{ secrets.PAT }}

    Deploy:
        needs: [Build]
        uses: aoda-zhang/shared-devops/.github/workflows/deploy_azure_service.yaml@master
        with:
            currentEnvironment: PROD
            build_name: honey-service-PROD
        secrets:
            PAT: ${{ secrets.PAT }}
            azure_service_name: ${{ secrets.AZURE_SERVICE_NAME }}
            AZURE_CLIENT_ID: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1AB49E4AB5FC4C8FB62DC28515294BD5 }}
            AZURE_TENANT_ID: ${{ secrets.AZUREAPPSERVICE_TENANTID_9E31CC84B7C74568864948CFAA04E942 }}
            AZURE_SUB_ID: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CE844279FA6049E88B1C730075A748B8 }}
